#!/usr/bin/env bash
#
# firebase-bootstrap.sh — one-shot setup of the Firebase backend for Recallr.
#
# Automates every CLI-scriptable step:
#   1. ensure firebase-tools is installed and you are logged in
#   2. create (or reuse) the Firebase project
#   3. create the default Firestore database
#   4. register a Web app and write its config into .env.local
#   5. deploy Firestore rules + indexes
#   6. build and deploy the app to Firebase Hosting
#
# The ONE step the CLI cannot do — enabling Google as a sign-in provider — is
# flagged with a clear pause so you can toggle it in the console.
#
# Usage:
#   ./scripts/firebase-bootstrap.sh [PROJECT_ID]
#
# If PROJECT_ID is omitted, a default is suggested. Re-running is safe: existing
# resources are detected and reused rather than recreated.

set -euo pipefail

PROJECT_ID="${1:-recallr-$(whoami 2>/dev/null | tr -cd 'a-z0-9' | cut -c1-8)-app}"
WEB_APP_NAME="Recallr Web"
FIRESTORE_LOCATION="${FIRESTORE_LOCATION:-nam5}"   # multi-region US; override via env
ENV_FILE=".env.local"

cyan()  { printf "\033[36m%s\033[0m\n" "$*"; }
green() { printf "\033[32m%s\033[0m\n" "$*"; }
yellow(){ printf "\033[33m%s\033[0m\n" "$*"; }
red()   { printf "\033[31m%s\033[0m\n" "$*"; }

# Run from the repo root regardless of where the script is invoked.
cd "$(dirname "$0")/.."

# ---------------------------------------------------------------------------
cyan "==> 1/6  firebase-tools + login"
if ! command -v firebase >/dev/null 2>&1; then
  yellow "firebase CLI not found. Installing globally (npm i -g firebase-tools)…"
  npm install -g firebase-tools
fi
if ! firebase login:list 2>/dev/null | grep -q '@'; then
  yellow "Not logged in. Opening browser for 'firebase login'…"
  firebase login
fi
green "Logged in as: $(firebase login:list 2>/dev/null | grep -o '[^ ]*@[^ ]*' | head -1)"

# ---------------------------------------------------------------------------
cyan "==> 2/6  Firebase project: ${PROJECT_ID}"
if firebase projects:list 2>/dev/null | grep -qw "${PROJECT_ID}"; then
  green "Project '${PROJECT_ID}' already exists — reusing."
else
  yellow "Creating project '${PROJECT_ID}'…"
  firebase projects:create "${PROJECT_ID}" --display-name "Recallr" || {
    red "Project creation failed (the ID may be taken globally). Re-run with a unique id:"
    red "  ./scripts/firebase-bootstrap.sh my-unique-recallr-id"
    exit 1
  }
fi
# Pin this repo to the project so subsequent commands don't need --project.
firebase use "${PROJECT_ID}" >/dev/null 2>&1 || firebase use --add "${PROJECT_ID}" || true

# ---------------------------------------------------------------------------
cyan "==> 3/6  Firestore database (location: ${FIRESTORE_LOCATION})"
if firebase firestore:databases:list --project "${PROJECT_ID}" 2>/dev/null | grep -q '(default)'; then
  green "Default Firestore database already exists — reusing."
else
  yellow "Creating default Firestore database…"
  firebase firestore:databases:create "(default)" \
    --location="${FIRESTORE_LOCATION}" --project "${PROJECT_ID}" || {
    red "Firestore creation failed. If this is a brand-new project, billing/consent"
    red "may need a one-time approval in the console, then re-run this script."
    exit 1
  }
fi

# ---------------------------------------------------------------------------
cyan "==> 4/6  Web app + .env.local"
# Ensure a Web app exists; capture its APP_ID.
APP_ID="$(firebase apps:list WEB --project "${PROJECT_ID}" 2>/dev/null \
  | grep -oE '1:[0-9]+:web:[a-z0-9]+' | head -1 || true)"
if [ -z "${APP_ID}" ]; then
  yellow "Registering Web app '${WEB_APP_NAME}'…"
  firebase apps:create WEB "${WEB_APP_NAME}" --project "${PROJECT_ID}" >/dev/null
  APP_ID="$(firebase apps:list WEB --project "${PROJECT_ID}" 2>/dev/null \
    | grep -oE '1:[0-9]+:web:[a-z0-9]+' | head -1)"
fi
green "Web app id: ${APP_ID}"

yellow "Fetching SDK config → ${ENV_FILE}"
CONFIG_JSON="$(firebase apps:sdkconfig WEB "${APP_ID}" --project "${PROJECT_ID}" 2>/dev/null \
  | sed -n '/{/,/}/p')"

# Extract values with node (already a dependency) for robust JSON parsing.
read_cfg() { node -e "try{const c=JSON.parse(process.argv[1]);process.stdout.write(String(c['$1']||''))}catch(e){}" "$CONFIG_JSON"; }

{
  echo "# Generated by scripts/firebase-bootstrap.sh — do not commit."
  echo "REACT_APP_FIREBASE_API_KEY=$(read_cfg apiKey)"
  echo "REACT_APP_FIREBASE_AUTH_DOMAIN=$(read_cfg authDomain)"
  echo "REACT_APP_FIREBASE_PROJECT_ID=$(read_cfg projectId)"
  echo "REACT_APP_FIREBASE_STORAGE_BUCKET=$(read_cfg storageBucket)"
  echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$(read_cfg messagingSenderId)"
  echo "REACT_APP_FIREBASE_APP_ID=$(read_cfg appId)"
} > "${ENV_FILE}"
green "Wrote ${ENV_FILE}"

# ---------------------------------------------------------------------------
red   "==> MANUAL STEP REQUIRED (the only one the CLI can't do)"
yellow "Enable Google Sign-In:"
yellow "  https://console.firebase.google.com/project/${PROJECT_ID}/authentication/providers"
yellow "  → Sign-in method → Add provider → Google → Enable → Save"
echo
read -r -p "Press Enter once Google Sign-In is enabled (or Ctrl+C to stop here)… " _ || true

# ---------------------------------------------------------------------------
cyan "==> 5/6  Deploy Firestore rules + indexes"
firebase deploy --only firestore:rules,firestore:indexes --project "${PROJECT_ID}"

# ---------------------------------------------------------------------------
cyan "==> 6/6  Build + deploy Hosting"
npm run build
firebase deploy --only hosting --project "${PROJECT_ID}"

echo
green "✅ Done. App live at: https://${PROJECT_ID}.web.app"
yellow "If sign-in is blocked, add that domain under Authentication → Settings → Authorized domains."
